### ISSUE TITLE
Error when loading model

### ISSUE THREAD

**Issue by Hoiy** [bheinzerling/bpemb#18]
Tried other lang and got the same error.

```>>> from bpemb import BPEmb
>>> bpemb_en = BPEmb(lang="en", dim=50)
downloading https://nlp.h-its.org/bpemb/en/en.wiki.bpe.vs10000.model
100%|████████████████████████████| 400869/400869 [00:00<00:00, 477001.39B/s]
downloading https://nlp.h-its.org/bpemb/en/en.wiki.bpe.vs10000.d50.w2v.bin.tar.gz
100%|█████████████████████████| 1924908/1924908 [00:01<00:00, 1202655.57B/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/bpemb/bpemb.py", line 149, in __init__
    assert self.dim == self.emb.vectors.shape[1]
AttributeError: 'KeyedVectors' object has no attribute 'vectors'

**Comment by bheinzerling** [comment]
Can you try upgrading to the latest version of gensim and see if you still get the error?

**Comment by Hoiy** [comment]
Thanks, it works!
